spring:
  application:
    name: "gatewayServer"
  config:
    import: "optional:configserver:http://localhost:8071/"
    # Config to connect with the eureka and get the MS details
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 10s
  # Connection redis of redis container
  data:
    redis:
      connect-timeout: 2s
      host: localhost
      port: 6379
      timeout: 1s

# Enable the actuator API paths
management:
  endpoints:
    web:
      exposure:
        include: "*"
  # Config to enable the gateway related endpoints for actuator
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

# information to view in the eureka dashboard
info:
  app:
    description: "Eazy Bank Gateway Server Application"
    name: "gatewayServer"
    version: "1.0.0"

logging:
  level:
    com:
      eazybytes:
        gatewayserver: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000