services:
  network-deploy-service:
    # Mention the network related configurations here
    networks:
      - "eazybank"

  microservice-base-config:
    # Whenever any Microservice we want to create inside docker compose it will extend this service.
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m

  microservice-configserver-config:
    # Any MS inside our application which depends on configserver will extend this service.
    extends:
      service: microservice-base-config
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071